
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
/**
 * Model Vote
 * 
 */
export type Vote = Prisma.VoteModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model Screenshot
 * 
 */
export type Screenshot = Prisma.ScreenshotModel
/**
 * Model ProjectTag
 * 
 */
export type ProjectTag = Prisma.ProjectTagModel
/**
 * Model Vote_Project
 * 
 */
export type Vote_Project = Prisma.Vote_ProjectModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
/**
 * Model Follow
 * 
 */
export type Follow = Prisma.FollowModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model AiAnalysis
 * 
 */
export type AiAnalysis = Prisma.AiAnalysisModel
