
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  user: 'user',
  admin: 'admin'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const PostStatus = {
  under_review: 'under_review',
  planned: 'planned',
  in_progress: 'in_progress',
  completed: 'completed'
} as const

export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus]


export const ProjectStatus = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED'
} as const

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus]


export const CommentType = {
  GENERAL: 'GENERAL',
  FEATURE_REQUEST: 'FEATURE_REQUEST',
  BUG_REPORT: 'BUG_REPORT'
} as const

export type CommentType = (typeof CommentType)[keyof typeof CommentType]
