
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AiAnalysis` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AiAnalysis
 * 
 */
export type AiAnalysisModel = runtime.Types.Result.DefaultSelection<Prisma.$AiAnalysisPayload>

export type AggregateAiAnalysis = {
  _count: AiAnalysisCountAggregateOutputType | null
  _min: AiAnalysisMinAggregateOutputType | null
  _max: AiAnalysisMaxAggregateOutputType | null
}

export type AiAnalysisMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  sentiment: string | null
  summary: string | null
  updatedAt: Date | null
}

export type AiAnalysisMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  sentiment: string | null
  summary: string | null
  updatedAt: Date | null
}

export type AiAnalysisCountAggregateOutputType = {
  id: number
  projectId: number
  sentiment: number
  topIssues: number
  featureRequests: number
  summary: number
  updatedAt: number
  _all: number
}


export type AiAnalysisMinAggregateInputType = {
  id?: true
  projectId?: true
  sentiment?: true
  summary?: true
  updatedAt?: true
}

export type AiAnalysisMaxAggregateInputType = {
  id?: true
  projectId?: true
  sentiment?: true
  summary?: true
  updatedAt?: true
}

export type AiAnalysisCountAggregateInputType = {
  id?: true
  projectId?: true
  sentiment?: true
  topIssues?: true
  featureRequests?: true
  summary?: true
  updatedAt?: true
  _all?: true
}

export type AiAnalysisAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AiAnalysis to aggregate.
   */
  where?: Prisma.AiAnalysisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiAnalyses to fetch.
   */
  orderBy?: Prisma.AiAnalysisOrderByWithRelationInput | Prisma.AiAnalysisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AiAnalysisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiAnalyses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiAnalyses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AiAnalyses
  **/
  _count?: true | AiAnalysisCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AiAnalysisMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AiAnalysisMaxAggregateInputType
}

export type GetAiAnalysisAggregateType<T extends AiAnalysisAggregateArgs> = {
      [P in keyof T & keyof AggregateAiAnalysis]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAiAnalysis[P]>
    : Prisma.GetScalarType<T[P], AggregateAiAnalysis[P]>
}




export type AiAnalysisGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AiAnalysisWhereInput
  orderBy?: Prisma.AiAnalysisOrderByWithAggregationInput | Prisma.AiAnalysisOrderByWithAggregationInput[]
  by: Prisma.AiAnalysisScalarFieldEnum[] | Prisma.AiAnalysisScalarFieldEnum
  having?: Prisma.AiAnalysisScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AiAnalysisCountAggregateInputType | true
  _min?: AiAnalysisMinAggregateInputType
  _max?: AiAnalysisMaxAggregateInputType
}

export type AiAnalysisGroupByOutputType = {
  id: string
  projectId: string
  sentiment: string
  topIssues: string[]
  featureRequests: string[]
  summary: string
  updatedAt: Date
  _count: AiAnalysisCountAggregateOutputType | null
  _min: AiAnalysisMinAggregateOutputType | null
  _max: AiAnalysisMaxAggregateOutputType | null
}

export type GetAiAnalysisGroupByPayload<T extends AiAnalysisGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AiAnalysisGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AiAnalysisGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AiAnalysisGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AiAnalysisGroupByOutputType[P]>
      }
    >
  >



export type AiAnalysisWhereInput = {
  AND?: Prisma.AiAnalysisWhereInput | Prisma.AiAnalysisWhereInput[]
  OR?: Prisma.AiAnalysisWhereInput[]
  NOT?: Prisma.AiAnalysisWhereInput | Prisma.AiAnalysisWhereInput[]
  id?: Prisma.StringFilter<"AiAnalysis"> | string
  projectId?: Prisma.StringFilter<"AiAnalysis"> | string
  sentiment?: Prisma.StringFilter<"AiAnalysis"> | string
  topIssues?: Prisma.StringNullableListFilter<"AiAnalysis">
  featureRequests?: Prisma.StringNullableListFilter<"AiAnalysis">
  summary?: Prisma.StringFilter<"AiAnalysis"> | string
  updatedAt?: Prisma.DateTimeFilter<"AiAnalysis"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type AiAnalysisOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  topIssues?: Prisma.SortOrder
  featureRequests?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type AiAnalysisWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  projectId?: string
  AND?: Prisma.AiAnalysisWhereInput | Prisma.AiAnalysisWhereInput[]
  OR?: Prisma.AiAnalysisWhereInput[]
  NOT?: Prisma.AiAnalysisWhereInput | Prisma.AiAnalysisWhereInput[]
  sentiment?: Prisma.StringFilter<"AiAnalysis"> | string
  topIssues?: Prisma.StringNullableListFilter<"AiAnalysis">
  featureRequests?: Prisma.StringNullableListFilter<"AiAnalysis">
  summary?: Prisma.StringFilter<"AiAnalysis"> | string
  updatedAt?: Prisma.DateTimeFilter<"AiAnalysis"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id" | "projectId">

export type AiAnalysisOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  topIssues?: Prisma.SortOrder
  featureRequests?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AiAnalysisCountOrderByAggregateInput
  _max?: Prisma.AiAnalysisMaxOrderByAggregateInput
  _min?: Prisma.AiAnalysisMinOrderByAggregateInput
}

export type AiAnalysisScalarWhereWithAggregatesInput = {
  AND?: Prisma.AiAnalysisScalarWhereWithAggregatesInput | Prisma.AiAnalysisScalarWhereWithAggregatesInput[]
  OR?: Prisma.AiAnalysisScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AiAnalysisScalarWhereWithAggregatesInput | Prisma.AiAnalysisScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AiAnalysis"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"AiAnalysis"> | string
  sentiment?: Prisma.StringWithAggregatesFilter<"AiAnalysis"> | string
  topIssues?: Prisma.StringNullableListFilter<"AiAnalysis">
  featureRequests?: Prisma.StringNullableListFilter<"AiAnalysis">
  summary?: Prisma.StringWithAggregatesFilter<"AiAnalysis"> | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AiAnalysis"> | Date | string
}

export type AiAnalysisCreateInput = {
  id?: string
  sentiment: string
  topIssues?: Prisma.AiAnalysisCreatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisCreatefeatureRequestsInput | string[]
  summary: string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutAiAnalysisInput
}

export type AiAnalysisUncheckedCreateInput = {
  id?: string
  projectId: string
  sentiment: string
  topIssues?: Prisma.AiAnalysisCreatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisCreatefeatureRequestsInput | string[]
  summary: string
  updatedAt?: Date | string
}

export type AiAnalysisUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.StringFieldUpdateOperationsInput | string
  topIssues?: Prisma.AiAnalysisUpdatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisUpdatefeatureRequestsInput | string[]
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutAiAnalysisNestedInput
}

export type AiAnalysisUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.StringFieldUpdateOperationsInput | string
  topIssues?: Prisma.AiAnalysisUpdatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisUpdatefeatureRequestsInput | string[]
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiAnalysisCreateManyInput = {
  id?: string
  projectId: string
  sentiment: string
  topIssues?: Prisma.AiAnalysisCreatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisCreatefeatureRequestsInput | string[]
  summary: string
  updatedAt?: Date | string
}

export type AiAnalysisUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.StringFieldUpdateOperationsInput | string
  topIssues?: Prisma.AiAnalysisUpdatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisUpdatefeatureRequestsInput | string[]
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiAnalysisUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.StringFieldUpdateOperationsInput | string
  topIssues?: Prisma.AiAnalysisUpdatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisUpdatefeatureRequestsInput | string[]
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiAnalysisNullableScalarRelationFilter = {
  is?: Prisma.AiAnalysisWhereInput | null
  isNot?: Prisma.AiAnalysisWhereInput | null
}

export type AiAnalysisCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  topIssues?: Prisma.SortOrder
  featureRequests?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AiAnalysisMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AiAnalysisMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AiAnalysisCreateNestedOneWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.AiAnalysisCreateWithoutProjectInput, Prisma.AiAnalysisUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.AiAnalysisCreateOrConnectWithoutProjectInput
  connect?: Prisma.AiAnalysisWhereUniqueInput
}

export type AiAnalysisUncheckedCreateNestedOneWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.AiAnalysisCreateWithoutProjectInput, Prisma.AiAnalysisUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.AiAnalysisCreateOrConnectWithoutProjectInput
  connect?: Prisma.AiAnalysisWhereUniqueInput
}

export type AiAnalysisUpdateOneWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.AiAnalysisCreateWithoutProjectInput, Prisma.AiAnalysisUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.AiAnalysisCreateOrConnectWithoutProjectInput
  upsert?: Prisma.AiAnalysisUpsertWithoutProjectInput
  disconnect?: Prisma.AiAnalysisWhereInput | boolean
  delete?: Prisma.AiAnalysisWhereInput | boolean
  connect?: Prisma.AiAnalysisWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AiAnalysisUpdateToOneWithWhereWithoutProjectInput, Prisma.AiAnalysisUpdateWithoutProjectInput>, Prisma.AiAnalysisUncheckedUpdateWithoutProjectInput>
}

export type AiAnalysisUncheckedUpdateOneWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.AiAnalysisCreateWithoutProjectInput, Prisma.AiAnalysisUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.AiAnalysisCreateOrConnectWithoutProjectInput
  upsert?: Prisma.AiAnalysisUpsertWithoutProjectInput
  disconnect?: Prisma.AiAnalysisWhereInput | boolean
  delete?: Prisma.AiAnalysisWhereInput | boolean
  connect?: Prisma.AiAnalysisWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AiAnalysisUpdateToOneWithWhereWithoutProjectInput, Prisma.AiAnalysisUpdateWithoutProjectInput>, Prisma.AiAnalysisUncheckedUpdateWithoutProjectInput>
}

export type AiAnalysisCreatetopIssuesInput = {
  set: string[]
}

export type AiAnalysisCreatefeatureRequestsInput = {
  set: string[]
}

export type AiAnalysisUpdatetopIssuesInput = {
  set?: string[]
  push?: string | string[]
}

export type AiAnalysisUpdatefeatureRequestsInput = {
  set?: string[]
  push?: string | string[]
}

export type AiAnalysisCreateWithoutProjectInput = {
  id?: string
  sentiment: string
  topIssues?: Prisma.AiAnalysisCreatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisCreatefeatureRequestsInput | string[]
  summary: string
  updatedAt?: Date | string
}

export type AiAnalysisUncheckedCreateWithoutProjectInput = {
  id?: string
  sentiment: string
  topIssues?: Prisma.AiAnalysisCreatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisCreatefeatureRequestsInput | string[]
  summary: string
  updatedAt?: Date | string
}

export type AiAnalysisCreateOrConnectWithoutProjectInput = {
  where: Prisma.AiAnalysisWhereUniqueInput
  create: Prisma.XOR<Prisma.AiAnalysisCreateWithoutProjectInput, Prisma.AiAnalysisUncheckedCreateWithoutProjectInput>
}

export type AiAnalysisUpsertWithoutProjectInput = {
  update: Prisma.XOR<Prisma.AiAnalysisUpdateWithoutProjectInput, Prisma.AiAnalysisUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.AiAnalysisCreateWithoutProjectInput, Prisma.AiAnalysisUncheckedCreateWithoutProjectInput>
  where?: Prisma.AiAnalysisWhereInput
}

export type AiAnalysisUpdateToOneWithWhereWithoutProjectInput = {
  where?: Prisma.AiAnalysisWhereInput
  data: Prisma.XOR<Prisma.AiAnalysisUpdateWithoutProjectInput, Prisma.AiAnalysisUncheckedUpdateWithoutProjectInput>
}

export type AiAnalysisUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.StringFieldUpdateOperationsInput | string
  topIssues?: Prisma.AiAnalysisUpdatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisUpdatefeatureRequestsInput | string[]
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiAnalysisUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.StringFieldUpdateOperationsInput | string
  topIssues?: Prisma.AiAnalysisUpdatetopIssuesInput | string[]
  featureRequests?: Prisma.AiAnalysisUpdatefeatureRequestsInput | string[]
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AiAnalysisSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  sentiment?: boolean
  topIssues?: boolean
  featureRequests?: boolean
  summary?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aiAnalysis"]>

export type AiAnalysisSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  sentiment?: boolean
  topIssues?: boolean
  featureRequests?: boolean
  summary?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aiAnalysis"]>

export type AiAnalysisSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  sentiment?: boolean
  topIssues?: boolean
  featureRequests?: boolean
  summary?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aiAnalysis"]>

export type AiAnalysisSelectScalar = {
  id?: boolean
  projectId?: boolean
  sentiment?: boolean
  topIssues?: boolean
  featureRequests?: boolean
  summary?: boolean
  updatedAt?: boolean
}

export type AiAnalysisOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "sentiment" | "topIssues" | "featureRequests" | "summary" | "updatedAt", ExtArgs["result"]["aiAnalysis"]>
export type AiAnalysisInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type AiAnalysisIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type AiAnalysisIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $AiAnalysisPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AiAnalysis"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    sentiment: string
    topIssues: string[]
    featureRequests: string[]
    summary: string
    updatedAt: Date
  }, ExtArgs["result"]["aiAnalysis"]>
  composites: {}
}

export type AiAnalysisGetPayload<S extends boolean | null | undefined | AiAnalysisDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload, S>

export type AiAnalysisCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AiAnalysisFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AiAnalysisCountAggregateInputType | true
  }

export interface AiAnalysisDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AiAnalysis'], meta: { name: 'AiAnalysis' } }
  /**
   * Find zero or one AiAnalysis that matches the filter.
   * @param {AiAnalysisFindUniqueArgs} args - Arguments to find a AiAnalysis
   * @example
   * // Get one AiAnalysis
   * const aiAnalysis = await prisma.aiAnalysis.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AiAnalysisFindUniqueArgs>(args: Prisma.SelectSubset<T, AiAnalysisFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AiAnalysis that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AiAnalysisFindUniqueOrThrowArgs} args - Arguments to find a AiAnalysis
   * @example
   * // Get one AiAnalysis
   * const aiAnalysis = await prisma.aiAnalysis.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AiAnalysisFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AiAnalysisFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AiAnalysis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiAnalysisFindFirstArgs} args - Arguments to find a AiAnalysis
   * @example
   * // Get one AiAnalysis
   * const aiAnalysis = await prisma.aiAnalysis.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AiAnalysisFindFirstArgs>(args?: Prisma.SelectSubset<T, AiAnalysisFindFirstArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AiAnalysis that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiAnalysisFindFirstOrThrowArgs} args - Arguments to find a AiAnalysis
   * @example
   * // Get one AiAnalysis
   * const aiAnalysis = await prisma.aiAnalysis.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AiAnalysisFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AiAnalysisFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AiAnalyses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiAnalysisFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AiAnalyses
   * const aiAnalyses = await prisma.aiAnalysis.findMany()
   * 
   * // Get first 10 AiAnalyses
   * const aiAnalyses = await prisma.aiAnalysis.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const aiAnalysisWithIdOnly = await prisma.aiAnalysis.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AiAnalysisFindManyArgs>(args?: Prisma.SelectSubset<T, AiAnalysisFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AiAnalysis.
   * @param {AiAnalysisCreateArgs} args - Arguments to create a AiAnalysis.
   * @example
   * // Create one AiAnalysis
   * const AiAnalysis = await prisma.aiAnalysis.create({
   *   data: {
   *     // ... data to create a AiAnalysis
   *   }
   * })
   * 
   */
  create<T extends AiAnalysisCreateArgs>(args: Prisma.SelectSubset<T, AiAnalysisCreateArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AiAnalyses.
   * @param {AiAnalysisCreateManyArgs} args - Arguments to create many AiAnalyses.
   * @example
   * // Create many AiAnalyses
   * const aiAnalysis = await prisma.aiAnalysis.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AiAnalysisCreateManyArgs>(args?: Prisma.SelectSubset<T, AiAnalysisCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AiAnalyses and returns the data saved in the database.
   * @param {AiAnalysisCreateManyAndReturnArgs} args - Arguments to create many AiAnalyses.
   * @example
   * // Create many AiAnalyses
   * const aiAnalysis = await prisma.aiAnalysis.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AiAnalyses and only return the `id`
   * const aiAnalysisWithIdOnly = await prisma.aiAnalysis.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AiAnalysisCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AiAnalysisCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AiAnalysis.
   * @param {AiAnalysisDeleteArgs} args - Arguments to delete one AiAnalysis.
   * @example
   * // Delete one AiAnalysis
   * const AiAnalysis = await prisma.aiAnalysis.delete({
   *   where: {
   *     // ... filter to delete one AiAnalysis
   *   }
   * })
   * 
   */
  delete<T extends AiAnalysisDeleteArgs>(args: Prisma.SelectSubset<T, AiAnalysisDeleteArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AiAnalysis.
   * @param {AiAnalysisUpdateArgs} args - Arguments to update one AiAnalysis.
   * @example
   * // Update one AiAnalysis
   * const aiAnalysis = await prisma.aiAnalysis.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AiAnalysisUpdateArgs>(args: Prisma.SelectSubset<T, AiAnalysisUpdateArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AiAnalyses.
   * @param {AiAnalysisDeleteManyArgs} args - Arguments to filter AiAnalyses to delete.
   * @example
   * // Delete a few AiAnalyses
   * const { count } = await prisma.aiAnalysis.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AiAnalysisDeleteManyArgs>(args?: Prisma.SelectSubset<T, AiAnalysisDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AiAnalyses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiAnalysisUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AiAnalyses
   * const aiAnalysis = await prisma.aiAnalysis.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AiAnalysisUpdateManyArgs>(args: Prisma.SelectSubset<T, AiAnalysisUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AiAnalyses and returns the data updated in the database.
   * @param {AiAnalysisUpdateManyAndReturnArgs} args - Arguments to update many AiAnalyses.
   * @example
   * // Update many AiAnalyses
   * const aiAnalysis = await prisma.aiAnalysis.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AiAnalyses and only return the `id`
   * const aiAnalysisWithIdOnly = await prisma.aiAnalysis.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AiAnalysisUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AiAnalysisUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AiAnalysis.
   * @param {AiAnalysisUpsertArgs} args - Arguments to update or create a AiAnalysis.
   * @example
   * // Update or create a AiAnalysis
   * const aiAnalysis = await prisma.aiAnalysis.upsert({
   *   create: {
   *     // ... data to create a AiAnalysis
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AiAnalysis we want to update
   *   }
   * })
   */
  upsert<T extends AiAnalysisUpsertArgs>(args: Prisma.SelectSubset<T, AiAnalysisUpsertArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AiAnalyses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiAnalysisCountArgs} args - Arguments to filter AiAnalyses to count.
   * @example
   * // Count the number of AiAnalyses
   * const count = await prisma.aiAnalysis.count({
   *   where: {
   *     // ... the filter for the AiAnalyses we want to count
   *   }
   * })
  **/
  count<T extends AiAnalysisCountArgs>(
    args?: Prisma.Subset<T, AiAnalysisCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AiAnalysisCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AiAnalysis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiAnalysisAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AiAnalysisAggregateArgs>(args: Prisma.Subset<T, AiAnalysisAggregateArgs>): Prisma.PrismaPromise<GetAiAnalysisAggregateType<T>>

  /**
   * Group by AiAnalysis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiAnalysisGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AiAnalysisGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AiAnalysisGroupByArgs['orderBy'] }
      : { orderBy?: AiAnalysisGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AiAnalysisGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAiAnalysisGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AiAnalysis model
 */
readonly fields: AiAnalysisFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AiAnalysis.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AiAnalysisClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AiAnalysis model
 */
export interface AiAnalysisFieldRefs {
  readonly id: Prisma.FieldRef<"AiAnalysis", 'String'>
  readonly projectId: Prisma.FieldRef<"AiAnalysis", 'String'>
  readonly sentiment: Prisma.FieldRef<"AiAnalysis", 'String'>
  readonly topIssues: Prisma.FieldRef<"AiAnalysis", 'String[]'>
  readonly featureRequests: Prisma.FieldRef<"AiAnalysis", 'String[]'>
  readonly summary: Prisma.FieldRef<"AiAnalysis", 'String'>
  readonly updatedAt: Prisma.FieldRef<"AiAnalysis", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AiAnalysis findUnique
 */
export type AiAnalysisFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * Filter, which AiAnalysis to fetch.
   */
  where: Prisma.AiAnalysisWhereUniqueInput
}

/**
 * AiAnalysis findUniqueOrThrow
 */
export type AiAnalysisFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * Filter, which AiAnalysis to fetch.
   */
  where: Prisma.AiAnalysisWhereUniqueInput
}

/**
 * AiAnalysis findFirst
 */
export type AiAnalysisFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * Filter, which AiAnalysis to fetch.
   */
  where?: Prisma.AiAnalysisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiAnalyses to fetch.
   */
  orderBy?: Prisma.AiAnalysisOrderByWithRelationInput | Prisma.AiAnalysisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AiAnalyses.
   */
  cursor?: Prisma.AiAnalysisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiAnalyses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiAnalyses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AiAnalyses.
   */
  distinct?: Prisma.AiAnalysisScalarFieldEnum | Prisma.AiAnalysisScalarFieldEnum[]
}

/**
 * AiAnalysis findFirstOrThrow
 */
export type AiAnalysisFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * Filter, which AiAnalysis to fetch.
   */
  where?: Prisma.AiAnalysisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiAnalyses to fetch.
   */
  orderBy?: Prisma.AiAnalysisOrderByWithRelationInput | Prisma.AiAnalysisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AiAnalyses.
   */
  cursor?: Prisma.AiAnalysisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiAnalyses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiAnalyses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AiAnalyses.
   */
  distinct?: Prisma.AiAnalysisScalarFieldEnum | Prisma.AiAnalysisScalarFieldEnum[]
}

/**
 * AiAnalysis findMany
 */
export type AiAnalysisFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * Filter, which AiAnalyses to fetch.
   */
  where?: Prisma.AiAnalysisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiAnalyses to fetch.
   */
  orderBy?: Prisma.AiAnalysisOrderByWithRelationInput | Prisma.AiAnalysisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AiAnalyses.
   */
  cursor?: Prisma.AiAnalysisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiAnalyses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiAnalyses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AiAnalyses.
   */
  distinct?: Prisma.AiAnalysisScalarFieldEnum | Prisma.AiAnalysisScalarFieldEnum[]
}

/**
 * AiAnalysis create
 */
export type AiAnalysisCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * The data needed to create a AiAnalysis.
   */
  data: Prisma.XOR<Prisma.AiAnalysisCreateInput, Prisma.AiAnalysisUncheckedCreateInput>
}

/**
 * AiAnalysis createMany
 */
export type AiAnalysisCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AiAnalyses.
   */
  data: Prisma.AiAnalysisCreateManyInput | Prisma.AiAnalysisCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AiAnalysis createManyAndReturn
 */
export type AiAnalysisCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * The data used to create many AiAnalyses.
   */
  data: Prisma.AiAnalysisCreateManyInput | Prisma.AiAnalysisCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AiAnalysis update
 */
export type AiAnalysisUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * The data needed to update a AiAnalysis.
   */
  data: Prisma.XOR<Prisma.AiAnalysisUpdateInput, Prisma.AiAnalysisUncheckedUpdateInput>
  /**
   * Choose, which AiAnalysis to update.
   */
  where: Prisma.AiAnalysisWhereUniqueInput
}

/**
 * AiAnalysis updateMany
 */
export type AiAnalysisUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AiAnalyses.
   */
  data: Prisma.XOR<Prisma.AiAnalysisUpdateManyMutationInput, Prisma.AiAnalysisUncheckedUpdateManyInput>
  /**
   * Filter which AiAnalyses to update
   */
  where?: Prisma.AiAnalysisWhereInput
  /**
   * Limit how many AiAnalyses to update.
   */
  limit?: number
}

/**
 * AiAnalysis updateManyAndReturn
 */
export type AiAnalysisUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * The data used to update AiAnalyses.
   */
  data: Prisma.XOR<Prisma.AiAnalysisUpdateManyMutationInput, Prisma.AiAnalysisUncheckedUpdateManyInput>
  /**
   * Filter which AiAnalyses to update
   */
  where?: Prisma.AiAnalysisWhereInput
  /**
   * Limit how many AiAnalyses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AiAnalysis upsert
 */
export type AiAnalysisUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * The filter to search for the AiAnalysis to update in case it exists.
   */
  where: Prisma.AiAnalysisWhereUniqueInput
  /**
   * In case the AiAnalysis found by the `where` argument doesn't exist, create a new AiAnalysis with this data.
   */
  create: Prisma.XOR<Prisma.AiAnalysisCreateInput, Prisma.AiAnalysisUncheckedCreateInput>
  /**
   * In case the AiAnalysis was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AiAnalysisUpdateInput, Prisma.AiAnalysisUncheckedUpdateInput>
}

/**
 * AiAnalysis delete
 */
export type AiAnalysisDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  /**
   * Filter which AiAnalysis to delete.
   */
  where: Prisma.AiAnalysisWhereUniqueInput
}

/**
 * AiAnalysis deleteMany
 */
export type AiAnalysisDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AiAnalyses to delete
   */
  where?: Prisma.AiAnalysisWhereInput
  /**
   * Limit how many AiAnalyses to delete.
   */
  limit?: number
}

/**
 * AiAnalysis without action
 */
export type AiAnalysisDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
}
