
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Project` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Project
 * 
 */
export type ProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectPayload>

export type AggregateProject = {
  _count: ProjectCountAggregateOutputType | null
  _avg: ProjectAvgAggregateOutputType | null
  _sum: ProjectSumAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

export type ProjectAvgAggregateOutputType = {
  views: number | null
}

export type ProjectSumAggregateOutputType = {
  views: number | null
}

export type ProjectMinAggregateOutputType = {
  id: string | null
  clerkUserId: string | null
  title: string | null
  slug: string | null
  tagline: string | null
  version: string | null
  description: string | null
  demoUrl: string | null
  repoUrl: string | null
  views: number | null
  status: $Enums.ProjectStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectMaxAggregateOutputType = {
  id: string | null
  clerkUserId: string | null
  title: string | null
  slug: string | null
  tagline: string | null
  version: string | null
  description: string | null
  demoUrl: string | null
  repoUrl: string | null
  views: number | null
  status: $Enums.ProjectStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectCountAggregateOutputType = {
  id: number
  clerkUserId: number
  title: number
  slug: number
  tagline: number
  version: number
  description: number
  demoUrl: number
  repoUrl: number
  languages: number
  frameworks: number
  views: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProjectAvgAggregateInputType = {
  views?: true
}

export type ProjectSumAggregateInputType = {
  views?: true
}

export type ProjectMinAggregateInputType = {
  id?: true
  clerkUserId?: true
  title?: true
  slug?: true
  tagline?: true
  version?: true
  description?: true
  demoUrl?: true
  repoUrl?: true
  views?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectMaxAggregateInputType = {
  id?: true
  clerkUserId?: true
  title?: true
  slug?: true
  tagline?: true
  version?: true
  description?: true
  demoUrl?: true
  repoUrl?: true
  views?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectCountAggregateInputType = {
  id?: true
  clerkUserId?: true
  title?: true
  slug?: true
  tagline?: true
  version?: true
  description?: true
  demoUrl?: true
  repoUrl?: true
  languages?: true
  frameworks?: true
  views?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Project to aggregate.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Projects
  **/
  _count?: true | ProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProjectAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProjectSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectMaxAggregateInputType
}

export type GetProjectAggregateType<T extends ProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProject[P]>
    : Prisma.GetScalarType<T[P], AggregateProject[P]>
}




export type ProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithAggregationInput | Prisma.ProjectOrderByWithAggregationInput[]
  by: Prisma.ProjectScalarFieldEnum[] | Prisma.ProjectScalarFieldEnum
  having?: Prisma.ProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectCountAggregateInputType | true
  _avg?: ProjectAvgAggregateInputType
  _sum?: ProjectSumAggregateInputType
  _min?: ProjectMinAggregateInputType
  _max?: ProjectMaxAggregateInputType
}

export type ProjectGroupByOutputType = {
  id: string
  clerkUserId: string
  title: string
  slug: string
  tagline: string | null
  version: string | null
  description: string
  demoUrl: string | null
  repoUrl: string | null
  languages: string[]
  frameworks: string[]
  views: number
  status: $Enums.ProjectStatus
  createdAt: Date
  updatedAt: Date
  _count: ProjectCountAggregateOutputType | null
  _avg: ProjectAvgAggregateOutputType | null
  _sum: ProjectSumAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

export type GetProjectGroupByPayload<T extends ProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
      }
    >
  >



export type ProjectWhereInput = {
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  id?: Prisma.StringFilter<"Project"> | string
  clerkUserId?: Prisma.StringFilter<"Project"> | string
  title?: Prisma.StringFilter<"Project"> | string
  slug?: Prisma.StringFilter<"Project"> | string
  tagline?: Prisma.StringNullableFilter<"Project"> | string | null
  version?: Prisma.StringNullableFilter<"Project"> | string | null
  description?: Prisma.StringFilter<"Project"> | string
  demoUrl?: Prisma.StringNullableFilter<"Project"> | string | null
  repoUrl?: Prisma.StringNullableFilter<"Project"> | string | null
  languages?: Prisma.StringNullableListFilter<"Project">
  frameworks?: Prisma.StringNullableListFilter<"Project">
  views?: Prisma.IntFilter<"Project"> | number
  status?: Prisma.EnumProjectStatusFilter<"Project"> | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  screenshots?: Prisma.ScreenshotListRelationFilter
  tags?: Prisma.ProjectTagListRelationFilter
  votes?: Prisma.Vote_ProjectListRelationFilter
  comments?: Prisma.CommentListRelationFilter
  aiAnalysis?: Prisma.XOR<Prisma.AiAnalysisNullableScalarRelationFilter, Prisma.AiAnalysisWhereInput> | null
}

export type ProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  tagline?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  demoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  repoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  languages?: Prisma.SortOrder
  frameworks?: Prisma.SortOrder
  views?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  screenshots?: Prisma.ScreenshotOrderByRelationAggregateInput
  tags?: Prisma.ProjectTagOrderByRelationAggregateInput
  votes?: Prisma.Vote_ProjectOrderByRelationAggregateInput
  comments?: Prisma.CommentOrderByRelationAggregateInput
  aiAnalysis?: Prisma.AiAnalysisOrderByWithRelationInput
}

export type ProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  clerkUserId?: Prisma.StringFilter<"Project"> | string
  title?: Prisma.StringFilter<"Project"> | string
  tagline?: Prisma.StringNullableFilter<"Project"> | string | null
  version?: Prisma.StringNullableFilter<"Project"> | string | null
  description?: Prisma.StringFilter<"Project"> | string
  demoUrl?: Prisma.StringNullableFilter<"Project"> | string | null
  repoUrl?: Prisma.StringNullableFilter<"Project"> | string | null
  languages?: Prisma.StringNullableListFilter<"Project">
  frameworks?: Prisma.StringNullableListFilter<"Project">
  views?: Prisma.IntFilter<"Project"> | number
  status?: Prisma.EnumProjectStatusFilter<"Project"> | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  screenshots?: Prisma.ScreenshotListRelationFilter
  tags?: Prisma.ProjectTagListRelationFilter
  votes?: Prisma.Vote_ProjectListRelationFilter
  comments?: Prisma.CommentListRelationFilter
  aiAnalysis?: Prisma.XOR<Prisma.AiAnalysisNullableScalarRelationFilter, Prisma.AiAnalysisWhereInput> | null
}, "id" | "slug">

export type ProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  tagline?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  demoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  repoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  languages?: Prisma.SortOrder
  frameworks?: Prisma.SortOrder
  views?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProjectCountOrderByAggregateInput
  _avg?: Prisma.ProjectAvgOrderByAggregateInput
  _max?: Prisma.ProjectMaxOrderByAggregateInput
  _min?: Prisma.ProjectMinOrderByAggregateInput
  _sum?: Prisma.ProjectSumOrderByAggregateInput
}

export type ProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Project"> | string
  clerkUserId?: Prisma.StringWithAggregatesFilter<"Project"> | string
  title?: Prisma.StringWithAggregatesFilter<"Project"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Project"> | string
  tagline?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  version?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  description?: Prisma.StringWithAggregatesFilter<"Project"> | string
  demoUrl?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  repoUrl?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  languages?: Prisma.StringNullableListFilter<"Project">
  frameworks?: Prisma.StringNullableListFilter<"Project">
  views?: Prisma.IntWithAggregatesFilter<"Project"> | number
  status?: Prisma.EnumProjectStatusWithAggregatesFilter<"Project"> | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Project"> | Date | string
}

export type ProjectCreateInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotUncheckedCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagUncheckedCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectUncheckedCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedCreateNestedOneWithoutProjectInput
}

export type ProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUncheckedUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUncheckedUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUncheckedUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedUpdateOneWithoutProjectNestedInput
}

export type ProjectCreateManyInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type ProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  tagline?: Prisma.SortOrder
  version?: Prisma.SortOrder
  description?: Prisma.SortOrder
  demoUrl?: Prisma.SortOrder
  repoUrl?: Prisma.SortOrder
  languages?: Prisma.SortOrder
  frameworks?: Prisma.SortOrder
  views?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectAvgOrderByAggregateInput = {
  views?: Prisma.SortOrder
}

export type ProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  tagline?: Prisma.SortOrder
  version?: Prisma.SortOrder
  description?: Prisma.SortOrder
  demoUrl?: Prisma.SortOrder
  repoUrl?: Prisma.SortOrder
  views?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  tagline?: Prisma.SortOrder
  version?: Prisma.SortOrder
  description?: Prisma.SortOrder
  demoUrl?: Prisma.SortOrder
  repoUrl?: Prisma.SortOrder
  views?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectSumOrderByAggregateInput = {
  views?: Prisma.SortOrder
}

export type ProjectScalarRelationFilter = {
  is?: Prisma.ProjectWhereInput
  isNot?: Prisma.ProjectWhereInput
}

export type ProjectCreatelanguagesInput = {
  set: string[]
}

export type ProjectCreateframeworksInput = {
  set: string[]
}

export type ProjectUpdatelanguagesInput = {
  set?: string[]
  push?: string | string[]
}

export type ProjectUpdateframeworksInput = {
  set?: string[]
  push?: string | string[]
}

export type EnumProjectStatusFieldUpdateOperationsInput = {
  set?: $Enums.ProjectStatus
}

export type ProjectCreateNestedOneWithoutScreenshotsInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutScreenshotsInput, Prisma.ProjectUncheckedCreateWithoutScreenshotsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutScreenshotsInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutScreenshotsNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutScreenshotsInput, Prisma.ProjectUncheckedCreateWithoutScreenshotsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutScreenshotsInput
  upsert?: Prisma.ProjectUpsertWithoutScreenshotsInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutScreenshotsInput, Prisma.ProjectUpdateWithoutScreenshotsInput>, Prisma.ProjectUncheckedUpdateWithoutScreenshotsInput>
}

export type ProjectCreateNestedOneWithoutTagsInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutTagsInput, Prisma.ProjectUncheckedCreateWithoutTagsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutTagsInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutTagsNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutTagsInput, Prisma.ProjectUncheckedCreateWithoutTagsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutTagsInput
  upsert?: Prisma.ProjectUpsertWithoutTagsInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutTagsInput, Prisma.ProjectUpdateWithoutTagsInput>, Prisma.ProjectUncheckedUpdateWithoutTagsInput>
}

export type ProjectCreateNestedOneWithoutVotesInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutVotesInput, Prisma.ProjectUncheckedCreateWithoutVotesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutVotesInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutVotesNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutVotesInput, Prisma.ProjectUncheckedCreateWithoutVotesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutVotesInput
  upsert?: Prisma.ProjectUpsertWithoutVotesInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutVotesInput, Prisma.ProjectUpdateWithoutVotesInput>, Prisma.ProjectUncheckedUpdateWithoutVotesInput>
}

export type ProjectCreateNestedOneWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutCommentsInput, Prisma.ProjectUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutCommentsInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutCommentsInput, Prisma.ProjectUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutCommentsInput
  upsert?: Prisma.ProjectUpsertWithoutCommentsInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutCommentsInput, Prisma.ProjectUpdateWithoutCommentsInput>, Prisma.ProjectUncheckedUpdateWithoutCommentsInput>
}

export type ProjectCreateNestedOneWithoutAiAnalysisInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutAiAnalysisInput, Prisma.ProjectUncheckedCreateWithoutAiAnalysisInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutAiAnalysisInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutAiAnalysisNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutAiAnalysisInput, Prisma.ProjectUncheckedCreateWithoutAiAnalysisInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutAiAnalysisInput
  upsert?: Prisma.ProjectUpsertWithoutAiAnalysisInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutAiAnalysisInput, Prisma.ProjectUpdateWithoutAiAnalysisInput>, Prisma.ProjectUncheckedUpdateWithoutAiAnalysisInput>
}

export type ProjectCreateWithoutScreenshotsInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tags?: Prisma.ProjectTagCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutScreenshotsInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tags?: Prisma.ProjectTagUncheckedCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectUncheckedCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedCreateNestedOneWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutScreenshotsInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutScreenshotsInput, Prisma.ProjectUncheckedCreateWithoutScreenshotsInput>
}

export type ProjectUpsertWithoutScreenshotsInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutScreenshotsInput, Prisma.ProjectUncheckedUpdateWithoutScreenshotsInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutScreenshotsInput, Prisma.ProjectUncheckedCreateWithoutScreenshotsInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutScreenshotsInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutScreenshotsInput, Prisma.ProjectUncheckedUpdateWithoutScreenshotsInput>
}

export type ProjectUpdateWithoutScreenshotsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tags?: Prisma.ProjectTagUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutScreenshotsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tags?: Prisma.ProjectTagUncheckedUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUncheckedUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedUpdateOneWithoutProjectNestedInput
}

export type ProjectCreateWithoutTagsInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutTagsInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotUncheckedCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectUncheckedCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedCreateNestedOneWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutTagsInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutTagsInput, Prisma.ProjectUncheckedCreateWithoutTagsInput>
}

export type ProjectUpsertWithoutTagsInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutTagsInput, Prisma.ProjectUncheckedUpdateWithoutTagsInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutTagsInput, Prisma.ProjectUncheckedCreateWithoutTagsInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutTagsInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutTagsInput, Prisma.ProjectUncheckedUpdateWithoutTagsInput>
}

export type ProjectUpdateWithoutTagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutTagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUncheckedUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUncheckedUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedUpdateOneWithoutProjectNestedInput
}

export type ProjectCreateWithoutVotesInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutVotesInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotUncheckedCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagUncheckedCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedCreateNestedOneWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutVotesInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutVotesInput, Prisma.ProjectUncheckedCreateWithoutVotesInput>
}

export type ProjectUpsertWithoutVotesInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutVotesInput, Prisma.ProjectUncheckedUpdateWithoutVotesInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutVotesInput, Prisma.ProjectUncheckedCreateWithoutVotesInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutVotesInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutVotesInput, Prisma.ProjectUncheckedUpdateWithoutVotesInput>
}

export type ProjectUpdateWithoutVotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutVotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUncheckedUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUncheckedUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedUpdateOneWithoutProjectNestedInput
}

export type ProjectCreateWithoutCommentsInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutCommentsInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotUncheckedCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagUncheckedCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectUncheckedCreateNestedManyWithoutProjectInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedCreateNestedOneWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutCommentsInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutCommentsInput, Prisma.ProjectUncheckedCreateWithoutCommentsInput>
}

export type ProjectUpsertWithoutCommentsInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutCommentsInput, Prisma.ProjectUncheckedUpdateWithoutCommentsInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutCommentsInput, Prisma.ProjectUncheckedCreateWithoutCommentsInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutCommentsInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutCommentsInput, Prisma.ProjectUncheckedUpdateWithoutCommentsInput>
}

export type ProjectUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUncheckedUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUncheckedUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUncheckedUpdateManyWithoutProjectNestedInput
  aiAnalysis?: Prisma.AiAnalysisUncheckedUpdateOneWithoutProjectNestedInput
}

export type ProjectCreateWithoutAiAnalysisInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentCreateNestedManyWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutAiAnalysisInput = {
  id?: string
  clerkUserId: string
  title: string
  slug: string
  tagline?: string | null
  version?: string | null
  description: string
  demoUrl?: string | null
  repoUrl?: string | null
  languages?: Prisma.ProjectCreatelanguagesInput | string[]
  frameworks?: Prisma.ProjectCreateframeworksInput | string[]
  views?: number
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  screenshots?: Prisma.ScreenshotUncheckedCreateNestedManyWithoutProjectInput
  tags?: Prisma.ProjectTagUncheckedCreateNestedManyWithoutProjectInput
  votes?: Prisma.Vote_ProjectUncheckedCreateNestedManyWithoutProjectInput
  comments?: Prisma.CommentUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutAiAnalysisInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutAiAnalysisInput, Prisma.ProjectUncheckedCreateWithoutAiAnalysisInput>
}

export type ProjectUpsertWithoutAiAnalysisInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutAiAnalysisInput, Prisma.ProjectUncheckedUpdateWithoutAiAnalysisInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutAiAnalysisInput, Prisma.ProjectUncheckedCreateWithoutAiAnalysisInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutAiAnalysisInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutAiAnalysisInput, Prisma.ProjectUncheckedUpdateWithoutAiAnalysisInput>
}

export type ProjectUpdateWithoutAiAnalysisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUpdateManyWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutAiAnalysisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  demoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  repoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languages?: Prisma.ProjectUpdatelanguagesInput | string[]
  frameworks?: Prisma.ProjectUpdateframeworksInput | string[]
  views?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  screenshots?: Prisma.ScreenshotUncheckedUpdateManyWithoutProjectNestedInput
  tags?: Prisma.ProjectTagUncheckedUpdateManyWithoutProjectNestedInput
  votes?: Prisma.Vote_ProjectUncheckedUpdateManyWithoutProjectNestedInput
  comments?: Prisma.CommentUncheckedUpdateManyWithoutProjectNestedInput
}


/**
 * Count Type ProjectCountOutputType
 */

export type ProjectCountOutputType = {
  screenshots: number
  tags: number
  votes: number
  comments: number
}

export type ProjectCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  screenshots?: boolean | ProjectCountOutputTypeCountScreenshotsArgs
  tags?: boolean | ProjectCountOutputTypeCountTagsArgs
  votes?: boolean | ProjectCountOutputTypeCountVotesArgs
  comments?: boolean | ProjectCountOutputTypeCountCommentsArgs
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCountOutputType
   */
  select?: Prisma.ProjectCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountScreenshotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ScreenshotWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountTagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectTagWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountVotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Vote_ProjectWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountCommentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CommentWhereInput
}


export type ProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clerkUserId?: boolean
  title?: boolean
  slug?: boolean
  tagline?: boolean
  version?: boolean
  description?: boolean
  demoUrl?: boolean
  repoUrl?: boolean
  languages?: boolean
  frameworks?: boolean
  views?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  screenshots?: boolean | Prisma.Project$screenshotsArgs<ExtArgs>
  tags?: boolean | Prisma.Project$tagsArgs<ExtArgs>
  votes?: boolean | Prisma.Project$votesArgs<ExtArgs>
  comments?: boolean | Prisma.Project$commentsArgs<ExtArgs>
  aiAnalysis?: boolean | Prisma.Project$aiAnalysisArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clerkUserId?: boolean
  title?: boolean
  slug?: boolean
  tagline?: boolean
  version?: boolean
  description?: boolean
  demoUrl?: boolean
  repoUrl?: boolean
  languages?: boolean
  frameworks?: boolean
  views?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["project"]>

export type ProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clerkUserId?: boolean
  title?: boolean
  slug?: boolean
  tagline?: boolean
  version?: boolean
  description?: boolean
  demoUrl?: boolean
  repoUrl?: boolean
  languages?: boolean
  frameworks?: boolean
  views?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["project"]>

export type ProjectSelectScalar = {
  id?: boolean
  clerkUserId?: boolean
  title?: boolean
  slug?: boolean
  tagline?: boolean
  version?: boolean
  description?: boolean
  demoUrl?: boolean
  repoUrl?: boolean
  languages?: boolean
  frameworks?: boolean
  views?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clerkUserId" | "title" | "slug" | "tagline" | "version" | "description" | "demoUrl" | "repoUrl" | "languages" | "frameworks" | "views" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["project"]>
export type ProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  screenshots?: boolean | Prisma.Project$screenshotsArgs<ExtArgs>
  tags?: boolean | Prisma.Project$tagsArgs<ExtArgs>
  votes?: boolean | Prisma.Project$votesArgs<ExtArgs>
  comments?: boolean | Prisma.Project$commentsArgs<ExtArgs>
  aiAnalysis?: boolean | Prisma.Project$aiAnalysisArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Project"
  objects: {
    screenshots: Prisma.$ScreenshotPayload<ExtArgs>[]
    tags: Prisma.$ProjectTagPayload<ExtArgs>[]
    votes: Prisma.$Vote_ProjectPayload<ExtArgs>[]
    comments: Prisma.$CommentPayload<ExtArgs>[]
    aiAnalysis: Prisma.$AiAnalysisPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clerkUserId: string
    title: string
    slug: string
    tagline: string | null
    version: string | null
    description: string
    demoUrl: string | null
    repoUrl: string | null
    languages: string[]
    frameworks: string[]
    views: number
    status: $Enums.ProjectStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["project"]>
  composites: {}
}

export type ProjectGetPayload<S extends boolean | null | undefined | ProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectPayload, S>

export type ProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectCountAggregateInputType | true
  }

export interface ProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Project'], meta: { name: 'Project' } }
  /**
   * Find zero or one Project that matches the filter.
   * @param {ProjectFindUniqueArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Project that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectFindUniqueOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Projects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Projects
   * const projects = await prisma.project.findMany()
   * 
   * // Get first 10 Projects
   * const projects = await prisma.project.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectWithIdOnly = await prisma.project.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Project.
   * @param {ProjectCreateArgs} args - Arguments to create a Project.
   * @example
   * // Create one Project
   * const Project = await prisma.project.create({
   *   data: {
   *     // ... data to create a Project
   *   }
   * })
   * 
   */
  create<T extends ProjectCreateArgs>(args: Prisma.SelectSubset<T, ProjectCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Projects.
   * @param {ProjectCreateManyArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Projects and returns the data saved in the database.
   * @param {ProjectCreateManyAndReturnArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Project.
   * @param {ProjectDeleteArgs} args - Arguments to delete one Project.
   * @example
   * // Delete one Project
   * const Project = await prisma.project.delete({
   *   where: {
   *     // ... filter to delete one Project
   *   }
   * })
   * 
   */
  delete<T extends ProjectDeleteArgs>(args: Prisma.SelectSubset<T, ProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Project.
   * @param {ProjectUpdateArgs} args - Arguments to update one Project.
   * @example
   * // Update one Project
   * const project = await prisma.project.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectUpdateArgs>(args: Prisma.SelectSubset<T, ProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Projects.
   * @param {ProjectDeleteManyArgs} args - Arguments to filter Projects to delete.
   * @example
   * // Delete a few Projects
   * const { count } = await prisma.project.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects and returns the data updated in the database.
   * @param {ProjectUpdateManyAndReturnArgs} args - Arguments to update many Projects.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Project.
   * @param {ProjectUpsertArgs} args - Arguments to update or create a Project.
   * @example
   * // Update or create a Project
   * const project = await prisma.project.upsert({
   *   create: {
   *     // ... data to create a Project
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Project we want to update
   *   }
   * })
   */
  upsert<T extends ProjectUpsertArgs>(args: Prisma.SelectSubset<T, ProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCountArgs} args - Arguments to filter Projects to count.
   * @example
   * // Count the number of Projects
   * const count = await prisma.project.count({
   *   where: {
   *     // ... the filter for the Projects we want to count
   *   }
   * })
  **/
  count<T extends ProjectCountArgs>(
    args?: Prisma.Subset<T, ProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectAggregateArgs>(args: Prisma.Subset<T, ProjectAggregateArgs>): Prisma.PrismaPromise<GetProjectAggregateType<T>>

  /**
   * Group by Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectGroupByArgs['orderBy'] }
      : { orderBy?: ProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Project model
 */
readonly fields: ProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Project.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  screenshots<T extends Prisma.Project$screenshotsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$screenshotsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScreenshotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tags<T extends Prisma.Project$tagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$tagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  votes<T extends Prisma.Project$votesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$votesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  comments<T extends Prisma.Project$commentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$commentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  aiAnalysis<T extends Prisma.Project$aiAnalysisArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$aiAnalysisArgs<ExtArgs>>): Prisma.Prisma__AiAnalysisClient<runtime.Types.Result.GetResult<Prisma.$AiAnalysisPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Project model
 */
export interface ProjectFieldRefs {
  readonly id: Prisma.FieldRef<"Project", 'String'>
  readonly clerkUserId: Prisma.FieldRef<"Project", 'String'>
  readonly title: Prisma.FieldRef<"Project", 'String'>
  readonly slug: Prisma.FieldRef<"Project", 'String'>
  readonly tagline: Prisma.FieldRef<"Project", 'String'>
  readonly version: Prisma.FieldRef<"Project", 'String'>
  readonly description: Prisma.FieldRef<"Project", 'String'>
  readonly demoUrl: Prisma.FieldRef<"Project", 'String'>
  readonly repoUrl: Prisma.FieldRef<"Project", 'String'>
  readonly languages: Prisma.FieldRef<"Project", 'String[]'>
  readonly frameworks: Prisma.FieldRef<"Project", 'String[]'>
  readonly views: Prisma.FieldRef<"Project", 'Int'>
  readonly status: Prisma.FieldRef<"Project", 'ProjectStatus'>
  readonly createdAt: Prisma.FieldRef<"Project", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Project", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Project findUnique
 */
export type ProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findUniqueOrThrow
 */
export type ProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findFirst
 */
export type ProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findFirstOrThrow
 */
export type ProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findMany
 */
export type ProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Projects to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project create
 */
export type ProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a Project.
   */
  data: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
}

/**
 * Project createMany
 */
export type ProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Project createManyAndReturn
 */
export type ProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Project update
 */
export type ProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a Project.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
  /**
   * Choose, which Project to update.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project updateMany
 */
export type ProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
}

/**
 * Project updateManyAndReturn
 */
export type ProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
}

/**
 * Project upsert
 */
export type ProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the Project to update in case it exists.
   */
  where: Prisma.ProjectWhereUniqueInput
  /**
   * In case the Project found by the `where` argument doesn't exist, create a new Project with this data.
   */
  create: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
  /**
   * In case the Project was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
}

/**
 * Project delete
 */
export type ProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter which Project to delete.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project deleteMany
 */
export type ProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Projects to delete
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to delete.
   */
  limit?: number
}

/**
 * Project.screenshots
 */
export type Project$screenshotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Screenshot
   */
  select?: Prisma.ScreenshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Screenshot
   */
  omit?: Prisma.ScreenshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScreenshotInclude<ExtArgs> | null
  where?: Prisma.ScreenshotWhereInput
  orderBy?: Prisma.ScreenshotOrderByWithRelationInput | Prisma.ScreenshotOrderByWithRelationInput[]
  cursor?: Prisma.ScreenshotWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ScreenshotScalarFieldEnum | Prisma.ScreenshotScalarFieldEnum[]
}

/**
 * Project.tags
 */
export type Project$tagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTag
   */
  select?: Prisma.ProjectTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTag
   */
  omit?: Prisma.ProjectTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTagInclude<ExtArgs> | null
  where?: Prisma.ProjectTagWhereInput
  orderBy?: Prisma.ProjectTagOrderByWithRelationInput | Prisma.ProjectTagOrderByWithRelationInput[]
  cursor?: Prisma.ProjectTagWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjectTagScalarFieldEnum | Prisma.ProjectTagScalarFieldEnum[]
}

/**
 * Project.votes
 */
export type Project$votesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  where?: Prisma.Vote_ProjectWhereInput
  orderBy?: Prisma.Vote_ProjectOrderByWithRelationInput | Prisma.Vote_ProjectOrderByWithRelationInput[]
  cursor?: Prisma.Vote_ProjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Vote_ProjectScalarFieldEnum | Prisma.Vote_ProjectScalarFieldEnum[]
}

/**
 * Project.comments
 */
export type Project$commentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comment
   */
  select?: Prisma.CommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comment
   */
  omit?: Prisma.CommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommentInclude<ExtArgs> | null
  where?: Prisma.CommentWhereInput
  orderBy?: Prisma.CommentOrderByWithRelationInput | Prisma.CommentOrderByWithRelationInput[]
  cursor?: Prisma.CommentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CommentScalarFieldEnum | Prisma.CommentScalarFieldEnum[]
}

/**
 * Project.aiAnalysis
 */
export type Project$aiAnalysisArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiAnalysis
   */
  select?: Prisma.AiAnalysisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiAnalysis
   */
  omit?: Prisma.AiAnalysisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiAnalysisInclude<ExtArgs> | null
  where?: Prisma.AiAnalysisWhereInput
}

/**
 * Project without action
 */
export type ProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
}
