
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Vote_Project` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Vote_Project
 * 
 */
export type Vote_ProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$Vote_ProjectPayload>

export type AggregateVote_Project = {
  _count: Vote_ProjectCountAggregateOutputType | null
  _avg: Vote_ProjectAvgAggregateOutputType | null
  _sum: Vote_ProjectSumAggregateOutputType | null
  _min: Vote_ProjectMinAggregateOutputType | null
  _max: Vote_ProjectMaxAggregateOutputType | null
}

export type Vote_ProjectAvgAggregateOutputType = {
  value: number | null
}

export type Vote_ProjectSumAggregateOutputType = {
  value: number | null
}

export type Vote_ProjectMinAggregateOutputType = {
  id: string | null
  clerkUserId: string | null
  projectId: string | null
  value: number | null
  createdAt: Date | null
}

export type Vote_ProjectMaxAggregateOutputType = {
  id: string | null
  clerkUserId: string | null
  projectId: string | null
  value: number | null
  createdAt: Date | null
}

export type Vote_ProjectCountAggregateOutputType = {
  id: number
  clerkUserId: number
  projectId: number
  value: number
  createdAt: number
  _all: number
}


export type Vote_ProjectAvgAggregateInputType = {
  value?: true
}

export type Vote_ProjectSumAggregateInputType = {
  value?: true
}

export type Vote_ProjectMinAggregateInputType = {
  id?: true
  clerkUserId?: true
  projectId?: true
  value?: true
  createdAt?: true
}

export type Vote_ProjectMaxAggregateInputType = {
  id?: true
  clerkUserId?: true
  projectId?: true
  value?: true
  createdAt?: true
}

export type Vote_ProjectCountAggregateInputType = {
  id?: true
  clerkUserId?: true
  projectId?: true
  value?: true
  createdAt?: true
  _all?: true
}

export type Vote_ProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Vote_Project to aggregate.
   */
  where?: Prisma.Vote_ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vote_Projects to fetch.
   */
  orderBy?: Prisma.Vote_ProjectOrderByWithRelationInput | Prisma.Vote_ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Vote_ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vote_Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vote_Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Vote_Projects
  **/
  _count?: true | Vote_ProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Vote_ProjectAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Vote_ProjectSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Vote_ProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Vote_ProjectMaxAggregateInputType
}

export type GetVote_ProjectAggregateType<T extends Vote_ProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateVote_Project]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVote_Project[P]>
    : Prisma.GetScalarType<T[P], AggregateVote_Project[P]>
}




export type Vote_ProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Vote_ProjectWhereInput
  orderBy?: Prisma.Vote_ProjectOrderByWithAggregationInput | Prisma.Vote_ProjectOrderByWithAggregationInput[]
  by: Prisma.Vote_ProjectScalarFieldEnum[] | Prisma.Vote_ProjectScalarFieldEnum
  having?: Prisma.Vote_ProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Vote_ProjectCountAggregateInputType | true
  _avg?: Vote_ProjectAvgAggregateInputType
  _sum?: Vote_ProjectSumAggregateInputType
  _min?: Vote_ProjectMinAggregateInputType
  _max?: Vote_ProjectMaxAggregateInputType
}

export type Vote_ProjectGroupByOutputType = {
  id: string
  clerkUserId: string
  projectId: string
  value: number
  createdAt: Date
  _count: Vote_ProjectCountAggregateOutputType | null
  _avg: Vote_ProjectAvgAggregateOutputType | null
  _sum: Vote_ProjectSumAggregateOutputType | null
  _min: Vote_ProjectMinAggregateOutputType | null
  _max: Vote_ProjectMaxAggregateOutputType | null
}

export type GetVote_ProjectGroupByPayload<T extends Vote_ProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Vote_ProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Vote_ProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Vote_ProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Vote_ProjectGroupByOutputType[P]>
      }
    >
  >



export type Vote_ProjectWhereInput = {
  AND?: Prisma.Vote_ProjectWhereInput | Prisma.Vote_ProjectWhereInput[]
  OR?: Prisma.Vote_ProjectWhereInput[]
  NOT?: Prisma.Vote_ProjectWhereInput | Prisma.Vote_ProjectWhereInput[]
  id?: Prisma.StringFilter<"Vote_Project"> | string
  clerkUserId?: Prisma.StringFilter<"Vote_Project"> | string
  projectId?: Prisma.StringFilter<"Vote_Project"> | string
  value?: Prisma.IntFilter<"Vote_Project"> | number
  createdAt?: Prisma.DateTimeFilter<"Vote_Project"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type Vote_ProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type Vote_ProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  clerkUserId_projectId?: Prisma.Vote_ProjectClerkUserIdProjectIdCompoundUniqueInput
  AND?: Prisma.Vote_ProjectWhereInput | Prisma.Vote_ProjectWhereInput[]
  OR?: Prisma.Vote_ProjectWhereInput[]
  NOT?: Prisma.Vote_ProjectWhereInput | Prisma.Vote_ProjectWhereInput[]
  clerkUserId?: Prisma.StringFilter<"Vote_Project"> | string
  projectId?: Prisma.StringFilter<"Vote_Project"> | string
  value?: Prisma.IntFilter<"Vote_Project"> | number
  createdAt?: Prisma.DateTimeFilter<"Vote_Project"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id" | "clerkUserId_projectId">

export type Vote_ProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.Vote_ProjectCountOrderByAggregateInput
  _avg?: Prisma.Vote_ProjectAvgOrderByAggregateInput
  _max?: Prisma.Vote_ProjectMaxOrderByAggregateInput
  _min?: Prisma.Vote_ProjectMinOrderByAggregateInput
  _sum?: Prisma.Vote_ProjectSumOrderByAggregateInput
}

export type Vote_ProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.Vote_ProjectScalarWhereWithAggregatesInput | Prisma.Vote_ProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.Vote_ProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Vote_ProjectScalarWhereWithAggregatesInput | Prisma.Vote_ProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Vote_Project"> | string
  clerkUserId?: Prisma.StringWithAggregatesFilter<"Vote_Project"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Vote_Project"> | string
  value?: Prisma.IntWithAggregatesFilter<"Vote_Project"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Vote_Project"> | Date | string
}

export type Vote_ProjectCreateInput = {
  id?: string
  clerkUserId: string
  value: number
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutVotesInput
}

export type Vote_ProjectUncheckedCreateInput = {
  id?: string
  clerkUserId: string
  projectId: string
  value: number
  createdAt?: Date | string
}

export type Vote_ProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutVotesNestedInput
}

export type Vote_ProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Vote_ProjectCreateManyInput = {
  id?: string
  clerkUserId: string
  projectId: string
  value: number
  createdAt?: Date | string
}

export type Vote_ProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Vote_ProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Vote_ProjectListRelationFilter = {
  every?: Prisma.Vote_ProjectWhereInput
  some?: Prisma.Vote_ProjectWhereInput
  none?: Prisma.Vote_ProjectWhereInput
}

export type Vote_ProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Vote_ProjectClerkUserIdProjectIdCompoundUniqueInput = {
  clerkUserId: string
  projectId: string
}

export type Vote_ProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type Vote_ProjectAvgOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type Vote_ProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type Vote_ProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type Vote_ProjectSumOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type Vote_ProjectCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.Vote_ProjectCreateWithoutProjectInput, Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput> | Prisma.Vote_ProjectCreateWithoutProjectInput[] | Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput | Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.Vote_ProjectCreateManyProjectInputEnvelope
  connect?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
}

export type Vote_ProjectUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.Vote_ProjectCreateWithoutProjectInput, Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput> | Prisma.Vote_ProjectCreateWithoutProjectInput[] | Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput | Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.Vote_ProjectCreateManyProjectInputEnvelope
  connect?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
}

export type Vote_ProjectUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.Vote_ProjectCreateWithoutProjectInput, Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput> | Prisma.Vote_ProjectCreateWithoutProjectInput[] | Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput | Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.Vote_ProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.Vote_ProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.Vote_ProjectCreateManyProjectInputEnvelope
  set?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  disconnect?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  delete?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  connect?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  update?: Prisma.Vote_ProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.Vote_ProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.Vote_ProjectUpdateManyWithWhereWithoutProjectInput | Prisma.Vote_ProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.Vote_ProjectScalarWhereInput | Prisma.Vote_ProjectScalarWhereInput[]
}

export type Vote_ProjectUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.Vote_ProjectCreateWithoutProjectInput, Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput> | Prisma.Vote_ProjectCreateWithoutProjectInput[] | Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput | Prisma.Vote_ProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.Vote_ProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.Vote_ProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.Vote_ProjectCreateManyProjectInputEnvelope
  set?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  disconnect?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  delete?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  connect?: Prisma.Vote_ProjectWhereUniqueInput | Prisma.Vote_ProjectWhereUniqueInput[]
  update?: Prisma.Vote_ProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.Vote_ProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.Vote_ProjectUpdateManyWithWhereWithoutProjectInput | Prisma.Vote_ProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.Vote_ProjectScalarWhereInput | Prisma.Vote_ProjectScalarWhereInput[]
}

export type Vote_ProjectCreateWithoutProjectInput = {
  id?: string
  clerkUserId: string
  value: number
  createdAt?: Date | string
}

export type Vote_ProjectUncheckedCreateWithoutProjectInput = {
  id?: string
  clerkUserId: string
  value: number
  createdAt?: Date | string
}

export type Vote_ProjectCreateOrConnectWithoutProjectInput = {
  where: Prisma.Vote_ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.Vote_ProjectCreateWithoutProjectInput, Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput>
}

export type Vote_ProjectCreateManyProjectInputEnvelope = {
  data: Prisma.Vote_ProjectCreateManyProjectInput | Prisma.Vote_ProjectCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type Vote_ProjectUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.Vote_ProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.Vote_ProjectUpdateWithoutProjectInput, Prisma.Vote_ProjectUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.Vote_ProjectCreateWithoutProjectInput, Prisma.Vote_ProjectUncheckedCreateWithoutProjectInput>
}

export type Vote_ProjectUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.Vote_ProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.Vote_ProjectUpdateWithoutProjectInput, Prisma.Vote_ProjectUncheckedUpdateWithoutProjectInput>
}

export type Vote_ProjectUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.Vote_ProjectScalarWhereInput
  data: Prisma.XOR<Prisma.Vote_ProjectUpdateManyMutationInput, Prisma.Vote_ProjectUncheckedUpdateManyWithoutProjectInput>
}

export type Vote_ProjectScalarWhereInput = {
  AND?: Prisma.Vote_ProjectScalarWhereInput | Prisma.Vote_ProjectScalarWhereInput[]
  OR?: Prisma.Vote_ProjectScalarWhereInput[]
  NOT?: Prisma.Vote_ProjectScalarWhereInput | Prisma.Vote_ProjectScalarWhereInput[]
  id?: Prisma.StringFilter<"Vote_Project"> | string
  clerkUserId?: Prisma.StringFilter<"Vote_Project"> | string
  projectId?: Prisma.StringFilter<"Vote_Project"> | string
  value?: Prisma.IntFilter<"Vote_Project"> | number
  createdAt?: Prisma.DateTimeFilter<"Vote_Project"> | Date | string
}

export type Vote_ProjectCreateManyProjectInput = {
  id?: string
  clerkUserId: string
  value: number
  createdAt?: Date | string
}

export type Vote_ProjectUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Vote_ProjectUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Vote_ProjectUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clerkUserId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type Vote_ProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clerkUserId?: boolean
  projectId?: boolean
  value?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vote_Project"]>

export type Vote_ProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clerkUserId?: boolean
  projectId?: boolean
  value?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vote_Project"]>

export type Vote_ProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clerkUserId?: boolean
  projectId?: boolean
  value?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vote_Project"]>

export type Vote_ProjectSelectScalar = {
  id?: boolean
  clerkUserId?: boolean
  projectId?: boolean
  value?: boolean
  createdAt?: boolean
}

export type Vote_ProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clerkUserId" | "projectId" | "value" | "createdAt", ExtArgs["result"]["vote_Project"]>
export type Vote_ProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type Vote_ProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type Vote_ProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $Vote_ProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Vote_Project"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clerkUserId: string
    projectId: string
    value: number
    createdAt: Date
  }, ExtArgs["result"]["vote_Project"]>
  composites: {}
}

export type Vote_ProjectGetPayload<S extends boolean | null | undefined | Vote_ProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload, S>

export type Vote_ProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Vote_ProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Vote_ProjectCountAggregateInputType | true
  }

export interface Vote_ProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Vote_Project'], meta: { name: 'Vote_Project' } }
  /**
   * Find zero or one Vote_Project that matches the filter.
   * @param {Vote_ProjectFindUniqueArgs} args - Arguments to find a Vote_Project
   * @example
   * // Get one Vote_Project
   * const vote_Project = await prisma.vote_Project.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Vote_ProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, Vote_ProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Vote_Project that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Vote_ProjectFindUniqueOrThrowArgs} args - Arguments to find a Vote_Project
   * @example
   * // Get one Vote_Project
   * const vote_Project = await prisma.vote_Project.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Vote_ProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Vote_ProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vote_Project that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Vote_ProjectFindFirstArgs} args - Arguments to find a Vote_Project
   * @example
   * // Get one Vote_Project
   * const vote_Project = await prisma.vote_Project.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Vote_ProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, Vote_ProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vote_Project that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Vote_ProjectFindFirstOrThrowArgs} args - Arguments to find a Vote_Project
   * @example
   * // Get one Vote_Project
   * const vote_Project = await prisma.vote_Project.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Vote_ProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Vote_ProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Vote_Projects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Vote_ProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Vote_Projects
   * const vote_Projects = await prisma.vote_Project.findMany()
   * 
   * // Get first 10 Vote_Projects
   * const vote_Projects = await prisma.vote_Project.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vote_ProjectWithIdOnly = await prisma.vote_Project.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Vote_ProjectFindManyArgs>(args?: Prisma.SelectSubset<T, Vote_ProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Vote_Project.
   * @param {Vote_ProjectCreateArgs} args - Arguments to create a Vote_Project.
   * @example
   * // Create one Vote_Project
   * const Vote_Project = await prisma.vote_Project.create({
   *   data: {
   *     // ... data to create a Vote_Project
   *   }
   * })
   * 
   */
  create<T extends Vote_ProjectCreateArgs>(args: Prisma.SelectSubset<T, Vote_ProjectCreateArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Vote_Projects.
   * @param {Vote_ProjectCreateManyArgs} args - Arguments to create many Vote_Projects.
   * @example
   * // Create many Vote_Projects
   * const vote_Project = await prisma.vote_Project.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Vote_ProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, Vote_ProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Vote_Projects and returns the data saved in the database.
   * @param {Vote_ProjectCreateManyAndReturnArgs} args - Arguments to create many Vote_Projects.
   * @example
   * // Create many Vote_Projects
   * const vote_Project = await prisma.vote_Project.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Vote_Projects and only return the `id`
   * const vote_ProjectWithIdOnly = await prisma.vote_Project.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Vote_ProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Vote_ProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Vote_Project.
   * @param {Vote_ProjectDeleteArgs} args - Arguments to delete one Vote_Project.
   * @example
   * // Delete one Vote_Project
   * const Vote_Project = await prisma.vote_Project.delete({
   *   where: {
   *     // ... filter to delete one Vote_Project
   *   }
   * })
   * 
   */
  delete<T extends Vote_ProjectDeleteArgs>(args: Prisma.SelectSubset<T, Vote_ProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Vote_Project.
   * @param {Vote_ProjectUpdateArgs} args - Arguments to update one Vote_Project.
   * @example
   * // Update one Vote_Project
   * const vote_Project = await prisma.vote_Project.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Vote_ProjectUpdateArgs>(args: Prisma.SelectSubset<T, Vote_ProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Vote_Projects.
   * @param {Vote_ProjectDeleteManyArgs} args - Arguments to filter Vote_Projects to delete.
   * @example
   * // Delete a few Vote_Projects
   * const { count } = await prisma.vote_Project.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Vote_ProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, Vote_ProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vote_Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Vote_ProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Vote_Projects
   * const vote_Project = await prisma.vote_Project.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Vote_ProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, Vote_ProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vote_Projects and returns the data updated in the database.
   * @param {Vote_ProjectUpdateManyAndReturnArgs} args - Arguments to update many Vote_Projects.
   * @example
   * // Update many Vote_Projects
   * const vote_Project = await prisma.vote_Project.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Vote_Projects and only return the `id`
   * const vote_ProjectWithIdOnly = await prisma.vote_Project.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Vote_ProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Vote_ProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Vote_Project.
   * @param {Vote_ProjectUpsertArgs} args - Arguments to update or create a Vote_Project.
   * @example
   * // Update or create a Vote_Project
   * const vote_Project = await prisma.vote_Project.upsert({
   *   create: {
   *     // ... data to create a Vote_Project
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Vote_Project we want to update
   *   }
   * })
   */
  upsert<T extends Vote_ProjectUpsertArgs>(args: Prisma.SelectSubset<T, Vote_ProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__Vote_ProjectClient<runtime.Types.Result.GetResult<Prisma.$Vote_ProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Vote_Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Vote_ProjectCountArgs} args - Arguments to filter Vote_Projects to count.
   * @example
   * // Count the number of Vote_Projects
   * const count = await prisma.vote_Project.count({
   *   where: {
   *     // ... the filter for the Vote_Projects we want to count
   *   }
   * })
  **/
  count<T extends Vote_ProjectCountArgs>(
    args?: Prisma.Subset<T, Vote_ProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Vote_ProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Vote_Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Vote_ProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Vote_ProjectAggregateArgs>(args: Prisma.Subset<T, Vote_ProjectAggregateArgs>): Prisma.PrismaPromise<GetVote_ProjectAggregateType<T>>

  /**
   * Group by Vote_Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Vote_ProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Vote_ProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Vote_ProjectGroupByArgs['orderBy'] }
      : { orderBy?: Vote_ProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Vote_ProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVote_ProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Vote_Project model
 */
readonly fields: Vote_ProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Vote_Project.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Vote_ProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Vote_Project model
 */
export interface Vote_ProjectFieldRefs {
  readonly id: Prisma.FieldRef<"Vote_Project", 'String'>
  readonly clerkUserId: Prisma.FieldRef<"Vote_Project", 'String'>
  readonly projectId: Prisma.FieldRef<"Vote_Project", 'String'>
  readonly value: Prisma.FieldRef<"Vote_Project", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Vote_Project", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Vote_Project findUnique
 */
export type Vote_ProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Vote_Project to fetch.
   */
  where: Prisma.Vote_ProjectWhereUniqueInput
}

/**
 * Vote_Project findUniqueOrThrow
 */
export type Vote_ProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Vote_Project to fetch.
   */
  where: Prisma.Vote_ProjectWhereUniqueInput
}

/**
 * Vote_Project findFirst
 */
export type Vote_ProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Vote_Project to fetch.
   */
  where?: Prisma.Vote_ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vote_Projects to fetch.
   */
  orderBy?: Prisma.Vote_ProjectOrderByWithRelationInput | Prisma.Vote_ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Vote_Projects.
   */
  cursor?: Prisma.Vote_ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vote_Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vote_Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vote_Projects.
   */
  distinct?: Prisma.Vote_ProjectScalarFieldEnum | Prisma.Vote_ProjectScalarFieldEnum[]
}

/**
 * Vote_Project findFirstOrThrow
 */
export type Vote_ProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Vote_Project to fetch.
   */
  where?: Prisma.Vote_ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vote_Projects to fetch.
   */
  orderBy?: Prisma.Vote_ProjectOrderByWithRelationInput | Prisma.Vote_ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Vote_Projects.
   */
  cursor?: Prisma.Vote_ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vote_Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vote_Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vote_Projects.
   */
  distinct?: Prisma.Vote_ProjectScalarFieldEnum | Prisma.Vote_ProjectScalarFieldEnum[]
}

/**
 * Vote_Project findMany
 */
export type Vote_ProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Vote_Projects to fetch.
   */
  where?: Prisma.Vote_ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vote_Projects to fetch.
   */
  orderBy?: Prisma.Vote_ProjectOrderByWithRelationInput | Prisma.Vote_ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Vote_Projects.
   */
  cursor?: Prisma.Vote_ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vote_Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vote_Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vote_Projects.
   */
  distinct?: Prisma.Vote_ProjectScalarFieldEnum | Prisma.Vote_ProjectScalarFieldEnum[]
}

/**
 * Vote_Project create
 */
export type Vote_ProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a Vote_Project.
   */
  data: Prisma.XOR<Prisma.Vote_ProjectCreateInput, Prisma.Vote_ProjectUncheckedCreateInput>
}

/**
 * Vote_Project createMany
 */
export type Vote_ProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Vote_Projects.
   */
  data: Prisma.Vote_ProjectCreateManyInput | Prisma.Vote_ProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Vote_Project createManyAndReturn
 */
export type Vote_ProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * The data used to create many Vote_Projects.
   */
  data: Prisma.Vote_ProjectCreateManyInput | Prisma.Vote_ProjectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Vote_Project update
 */
export type Vote_ProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a Vote_Project.
   */
  data: Prisma.XOR<Prisma.Vote_ProjectUpdateInput, Prisma.Vote_ProjectUncheckedUpdateInput>
  /**
   * Choose, which Vote_Project to update.
   */
  where: Prisma.Vote_ProjectWhereUniqueInput
}

/**
 * Vote_Project updateMany
 */
export type Vote_ProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Vote_Projects.
   */
  data: Prisma.XOR<Prisma.Vote_ProjectUpdateManyMutationInput, Prisma.Vote_ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Vote_Projects to update
   */
  where?: Prisma.Vote_ProjectWhereInput
  /**
   * Limit how many Vote_Projects to update.
   */
  limit?: number
}

/**
 * Vote_Project updateManyAndReturn
 */
export type Vote_ProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * The data used to update Vote_Projects.
   */
  data: Prisma.XOR<Prisma.Vote_ProjectUpdateManyMutationInput, Prisma.Vote_ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Vote_Projects to update
   */
  where?: Prisma.Vote_ProjectWhereInput
  /**
   * Limit how many Vote_Projects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Vote_Project upsert
 */
export type Vote_ProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the Vote_Project to update in case it exists.
   */
  where: Prisma.Vote_ProjectWhereUniqueInput
  /**
   * In case the Vote_Project found by the `where` argument doesn't exist, create a new Vote_Project with this data.
   */
  create: Prisma.XOR<Prisma.Vote_ProjectCreateInput, Prisma.Vote_ProjectUncheckedCreateInput>
  /**
   * In case the Vote_Project was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Vote_ProjectUpdateInput, Prisma.Vote_ProjectUncheckedUpdateInput>
}

/**
 * Vote_Project delete
 */
export type Vote_ProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
  /**
   * Filter which Vote_Project to delete.
   */
  where: Prisma.Vote_ProjectWhereUniqueInput
}

/**
 * Vote_Project deleteMany
 */
export type Vote_ProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Vote_Projects to delete
   */
  where?: Prisma.Vote_ProjectWhereInput
  /**
   * Limit how many Vote_Projects to delete.
   */
  limit?: number
}

/**
 * Vote_Project without action
 */
export type Vote_ProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote_Project
   */
  select?: Prisma.Vote_ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote_Project
   */
  omit?: Prisma.Vote_ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Vote_ProjectInclude<ExtArgs> | null
}
